---
- hosts: localhost
  connection: local
  become: true
  pre_tasks:
  - name: Update Apt
    become: true
    apt:
      update_cache: true
      state: latest
    tags:
      - install
      - update
      - local
  tasks:
    - include: tasks/git.yml
    - include: tasks/zsh.yml
    - include: tasks/brave.yml
    - include: tasks/edge.yml
    - include: tasks/cleanup.yml
    
    - include: tasks/core-setup.yml
    - include: tasks/node-setup.yml
    - include: tasks/npm-packages.yml
    - include: tasks/zsh-setup.yml
    - include: tasks/personal-projects.yml
    - include: tasks/nvim-setup.yml
    - include: tasks/debugger.yml
    - include: tasks/dotfiles.yml
    - include: tasks/productivity-tools.yml
    - include: tasks/lsp.yml
