---
- hosts: localhost
  connection: local
  become: true
  pre_tasks:
  - name: Update Apt
    become: true
    apt:
      update_cache: true
      state: latest
    tags:
      - install
      - update
      - local
  tasks:
    - import_tasks: tasks/git.yml
    - import_tasks: tasks/simplepackages.yml
    - import_tasks: tasks/brave.yml
    - import_tasks: tasks/cleanup.yml
