- name: PreReq Libraries for Edge
  become: true
  apt:
    update_cache: true
    name: 
      - curl
      - apt-transport-https
    state: latest
    tags:
      - edge
      - prereqs
      - install
- name: Add apt signing key
    ansible.builtin.apt_key:
      url: "https://packages.microsoft.com/keys/microsoft.asc"
      state: latest
      tags:
        - edge
        - install
- name: Add repository into sources list
    ansible.builtin.apt_repository:
      repo: deb [arch=amd64] https://packages.microsoft.com/repos/edge stable main
      state: latest
      filename: microsoft-edge
      tags:
        - edge
        - install
- name: Edge Browser Install
    ansible.builtin.apt:
      name: "microsoft-edge-stable"
      state: latest
      update_cache: true
      tags:
        - edge
        - install
