---
- hosts: localhost
  connection: local
  become: true
  pre_tasks:
  - name: Update Apt
    become: true
    apt:
      update_cache: true
      state: latest
    tags:
      - install
      - update
      - local
  tasks:
    - name: PreReq Libraries for Edge
      apt:
        name: 
          - curl
          - apt-transport-https
        state: latest
        update_cache: true
    - name: Add apt signing key
      apt_key:
        url: "https://packages.microsoft.com/keys/microsoft.asc"
        state: present
    - name: Add edge repository into sources list
      apt_repository:
        repo: deb [arch=amd64] https://packages.microsoft.com/repos/edge stable main
        state: present
        filename: microsoft-edge
    - name: Edge Browser Install
      apt:
        name: "microsoft-edge-stable"
        state: latest
        update_cache: true
