---
- hosts: localhost
  connection: local
  become: true
  pre_tasks:
  - name: Update Apt
    become: true
    apt:
      update_cache: true
      state: latest
    tags:
      - install
      - update
      - local
  tasks:
  - name: Install packages
    apt:
      name:
        - neovim
      update_cache: true
      state: latest
    tags:
      - install
      - neovim
      - packages
      - breakout
