---
- hosts: localhost
  connection: local
  become: true
  pre_tasks:
  - name: Update Apt
    become: true
    apt:
      update_cache: true
      state: latest
    tags:
      - install
      - update
      - local
  tasks:
  - name: Install packages
    apt:
      name:
        - chromium-browser
        - ffmpeg
        - fzf
        - gimp
        - i3
        - mpv
        - neovim
        - nmap
        - redshift
        - ripgrep
        - screenkey
        - shutter
        - stow
        - tldr
        - tmux
        - wavemon
        - wireshark
        - zsh
      update_cache: true
      state: latest
    tags:
      - install
      - simple
      - packages
      - breakout
